spring.application.name=avis-sort-DGI
# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/avis_sort_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Chemin REP

rep.in=src/main/resources/REP/IN
rep.out=C:/avis-sort-DGI/avis-sort-DGI/src/main/resources/REP/OUT

rep.archive=src/main/resources/REP/ARCHIVE
rep.log=src/main/resources/REP/LOG

