spring.application.name=avis-sort-DGI
# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/avis_sort_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Chemin REP

rep.in=C:/avis-sort-DGI/backend/src/main/resources/REP/IN
rep.out=C:/avis-sort-DGI/backend/src/main/resources/REP/OUT
rep.archive=C:/avis-sort-DGI/backend/src/main/resources/REP/ARCHIVE
rep.log=C:/avis-sort-DGI/backend/src/main/resources/REP/LOG

# Taille maximale autorisée pour un seul fichier envoyé dans la requête
spring.servlet.multipart.max-file-size=10MB
# Taille maximale autorisée pour la requête HTTP entière
spring.servlet.multipart.max-request-size=10MB

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=alezregue@gmail.com
spring.mail.password=akmivgqhysysxbrr
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

app.mail.from=alezregue@gmail.com